### ISSUE TITLE
Pact incompatible with rspec 2.12.2

### ISSUE THREAD

**Issue by Catharz** [realestate-com-au/pact#92]
Getting the following error using pact with a ruby 1.9.3 project and rspec 2.12.2.

```
rake pact:verify
/opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/provider/pact_spec_runner.rb:60:in `configure_rspec': undefined method `backtrace_inclusion_patterns=' for #<RSpec::Core::Configuration:0x007fd43cd27e50> (NoMethodError)
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/provider/pact_spec_runner.rb:33:in `run'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/app.rb:82:in `run_with_configured_pacts'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/app.rb:69:in `run_specs'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/app.rb:50:in `call'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/app.rb:43:in `call'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/lib/pact/app.rb:15:in `verify'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/rubies/1.9.3-p547/lib/ruby/gems/1.9.1/gems/pact-1.1.1/bin/pact:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/1.9.3-p547/bin/pact:23:in `load'
	from /opt/boxen/rbenv/versions/1.9.3-p547/bin/pact:23:in `<main>'
```

I searched through the gem folder for rspec 2.12.2 and the method `backtrace_inclusion_patterns` does not exist.

**Comment by Catharz** [comment]
After some more investigation, this seems like it might be an environmental issue with this project.

Closing this issue.
